# Generated by Django 3.0.5 on 2020-04-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='xlist_app.ShoppingList'),
        ),
    ]
