# Generated by Django 3.0.5 on 2020-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xlist_app', '0002_auto_20200417_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
