# Generated by Django 3.0.5 on 2020-06-23 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xlist_app', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskForShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='what_list', to='xlist_app.ShoppingList')),
                ('who_asked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_asked', to=settings.AUTH_USER_MODEL)),
                ('whos_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whos_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
