# Generated by Django 3.0.5 on 2020-06-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xlist_app', '0004_askforshare'),
        ('xlist_app', '0004_auto_20200417_1746'),
    ]

    operations = [
    ]
